steps:
  - name: 'gcr.io/google.com/cloudsdk/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mcgi-back' # Your Cloud Run service name
      - '--source'
      - '.'       # Use the current directory as the source
      - '--region'
      - 'us-central1' # Your Cloud Run region
      - '--platform'
      - 'managed'
      - '--ingress=all'  # Or internal, etc.
      - '--port=8080' # The port your app listens on
      - '--allow-unauthenticated' # If unauthenticated access is needed

options:
  machineType: 'E2_HIGHCPU_8'

serviceAccount: '751732416354-compute@developer.gserviceaccount.com' # Replace if different