steps:
  - name: 'node:20.18.2'
    entrypoint: 'npm'
    args: ['install']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mcgi-back:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mcgi-back:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdk/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mcgi-back'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mcgi-back:$COMMIT_SHA'
      - '--region'
      - 'us-central1' # Or your preferred region
      - '--platform'
      - 'managed'
      - '--ingress=all'  # Or '--ingress=internal' etc. as needed
      - '--port=8080' # Set the port directly in the gcloud command

options:
  machineType: 'E2_HIGHCPU_8'

serviceAccount: '751732416354-compute@developer.gserviceaccount.com'