steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['run', 'build'] # If you have a build script
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mcgi-back:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mcgi-back:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdk/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mcgi-back'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mcgi-back:$COMMIT_SHA'
      - '--region'
      - 'us-central1' # Replace with your region
      - '--platform'
      - 'managed'
      - '--ingress=all' # Or '--ingress=internal' for authenticated access
    env:
      - 'PORT=8080' # Set the port for Cloud Run

options:
  machineType: 'E2_HIGHCPU_8'

serviceAccount: '751732416354-compute@developer.gserviceaccount.com' # Replace with your service account