steps:
  - name: 'node:20.18.2'
    entrypoint: 'npm'
    args: ['install']

  # Deploy to Cloud Run directly from source
  - name: 'gcr.io/google.com/cloudsdk/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mcgi-back'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--ingress=all'
      - '--port=8080'
      - '--allow-unauthenticated' # Add if needed

options:
  machineType: 'E2_HIGHCPU_8'

serviceAccount: '751732416354-compute@developer.gserviceaccount.com'