# steps:
# - name: 'gcr.io/cloud-builders/npm'
#   entrypoint: 'npm'
#   args: ['install']
# - name: 'gcr.io/cloud-builders/npm'
#   entrypoint: 'npm'
#   args: ['run', 'build']

# options:
#   machineType: 'E2_HIGHCPU_8' # Optional: For faster builds

# # Service account configuration
# serviceAccount: 'mcgifeastlogin@mcgifeastprinting.iam.gserviceaccount.com' # Replace with your service account email



steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'npm'
  args: ['run', 'build']
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mcgi-back:$COMMIT_SHA', '.']
# Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mcgi-back:$COMMIT_SHA']
# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdk/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'mcgi-back' # Your service name
    - '--image'
    - 'gcr.io/$PROJECT_ID/mcgi-back:$COMMIT_SHA'
    - '--region'
    - 'YOUR_REGION' # Replace with your region
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated' # Or remove this line for authentication

options:
  machineType: 'E2_HIGHCPU_8'

serviceAccount: 'mcgifeastlogin@mcgifeastprinting.iam.gserviceaccount.com'