steps:
  - name: 'gcr.io/google.com/cloudsdk/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mcgi-back' # Your service name
      - '--source'
      - '.'       # Deploy from the current directory
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--ingress=all' # Or internal, etc.
      - '--port=8080'  # The port your app listens on
      - '--allow-unauthenticated' # If needed

options:
  machineType: 'E2_HIGHCPU_8'

serviceAccount: '751732416354-compute@developer.gserviceaccount.com' # Replace if different