steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'npm'
  args: ['run', 'build']

options:
  machineType: 'E2_HIGHCPU_8' # Optional: For faster builds

# Service account configuration
serviceAccount: 'mcgifeastlogin@mcgifeastprinting.iam.gserviceaccount.com' # Replace with your service account email

